### ISSUE TITLE
Incorrect error message when attempting to remove a team

### ISSUE THREAD

**Issue by zaki-amin** [impaas/docs#1]
As a regular user, I am able to create a team but I cannot remove it. The error message is misleading or incorrect: I am able to list the team and it exists, however, the error message implies that it does not.

```
❯ tsuru team list             
+------------+-------------+------+
| Team       | Permissions | Tags |
+------------+-------------+------+
| doc-edtech | app         |      |
+------------+-------------+------+
```

`❯ tsuru team remove doc-edtech
Are you sure you want to remove team "doc-edtech"? (y/n) y
Error: Delete "https://impaas.uk/1.0/teams/doc-edtech": Team "doc-edtech" not found.
`

**Comment by rushil-ambati** [comment]
Please open an upstream issue for this at [github.com/tsuru/tsuru/issues](https://github.com/tsuru/tsuru/issues)
